// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usersdb

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/rx-refill-reminders/users/postconfirm-lambda/src/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockClient
func (_mock *MockClient) CreateUser(ctx context.Context, user model.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *MockClient_Expecter) CreateUser(ctx interface{}, user interface{}) *MockClient_CreateUser_Call {
	return &MockClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockClient_CreateUser_Call) Run(run func(ctx context.Context, user model.User)) *MockClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_CreateUser_Call) Return(err error) *MockClient_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) error) *MockClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDynamoInterface creates a new instance of MockDynamoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDynamoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDynamoInterface {
	mock := &MockDynamoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDynamoInterface is an autogenerated mock type for the DynamoInterface type
type MockDynamoInterface struct {
	mock.Mock
}

type MockDynamoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDynamoInterface) EXPECT() *MockDynamoInterface_Expecter {
	return &MockDynamoInterface_Expecter{mock: &_m.Mock}
}

// PutItem provides a mock function for the type MockDynamoInterface
func (_mock *MockDynamoInterface) PutItem(ctx context.Context, params *dynamodb.PutItemInput, optFns ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutItem")
	}

	var r0 *dynamodb.PutItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) *dynamodb.PutItemOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.PutItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDynamoInterface_PutItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutItem'
type MockDynamoInterface_PutItem_Call struct {
	*mock.Call
}

// PutItem is a helper method to define mock.On call
//   - ctx context.Context
//   - params *dynamodb.PutItemInput
//   - optFns ...func(*dynamodb.Options)
func (_e *MockDynamoInterface_Expecter) PutItem(ctx interface{}, params interface{}, optFns ...interface{}) *MockDynamoInterface_PutItem_Call {
	return &MockDynamoInterface_PutItem_Call{Call: _e.mock.On("PutItem",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockDynamoInterface_PutItem_Call) Run(run func(ctx context.Context, params *dynamodb.PutItemInput, optFns ...func(*dynamodb.Options))) *MockDynamoInterface_PutItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.PutItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.PutItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDynamoInterface_PutItem_Call) Return(putItemOutput *dynamodb.PutItemOutput, err error) *MockDynamoInterface_PutItem_Call {
	_c.Call.Return(putItemOutput, err)
	return _c
}

func (_c *MockDynamoInterface_PutItem_Call) RunAndReturn(run func(ctx context.Context, params *dynamodb.PutItemInput, optFns ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)) *MockDynamoInterface_PutItem_Call {
	_c.Call.Return(run)
	return _c
}
